apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: newshub-hpa
  namespace: newshub
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: newshub-deployment
  minReplicas: 1
  maxReplicas: 4

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
